object Dependence {
    private val appCompatVersion = "1.7.0-alpha02"
    private val coreVersion = "1.9.0"
    private val materialVersion = "1.9.0-alpha02"
    private val recyclerViewVersion = "1.3.0-rc01"
    private val constraintLayoutVersion = "2.2.0-alpha07"
    private val preferenceVersion = "1.2.0"
    private val fragmentVersion = "1.6.0-alpha05"
    private val splashScreenVersion = "1.0.1"
    private val retrofitVersion = "2.9.0"
    private val loggingInterceptorVersion = "4.10.0"
    private val rxJavaVersion = "2.2.21"
    private val rxAndroidVersion = "2.1.1"
    private val lifecycleVersion = "2.2.0"
    private val roomVersion = "2.5.0"
    private val stethoVersion = "1.6.0"
    private val leakCanaryVersion = "2.10"
    private val gsonVersion = "2.8.5"
    private val glideVersion = "4.14.2"
    private val chuckerVersion = "3.5.2"

    val kotlin = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Version.kotlin}"
    val appCompat = "androidx.appcompat:appcompat:$appCompatVersion"
    val core = "androidx.core:core:$coreVersion"
    val material = "com.google.android.material:material:$materialVersion"
    val recyclerview = "androidx.recyclerview:recyclerview:$recyclerViewVersion"
    val constraintLayout = "androidx.constraintlayout:constraintlayout:$constraintLayoutVersion"
    val preference = "androidx.preference:preference-ktx:$preferenceVersion"
    val navigation = "androidx.navigation:navigation-ui-ktx:${Version.navigation}"
    val navigationFragment = "androidx.navigation:navigation-fragment-ktx:${Version.navigation}"
    val fragment = "androidx.fragment:fragment-ktx:$fragmentVersion"
    val splashScreen = "androidx.core:core-splashscreen:$splashScreenVersion"

    val rxJava = "io.reactivex.rxjava2:rxjava:$rxJavaVersion"
    val rxAndroid = "io.reactivex.rxjava2:rxandroid:$rxAndroidVersion"
    val retrofit = "com.squareup.retrofit2:retrofit:$retrofitVersion"
    val retrofitConverterGson = "com.squareup.retrofit2:converter-gson:$retrofitVersion"
    val retrofitRxJava = "com.squareup.retrofit2:adapter-rxjava2:$retrofitVersion"
    val loggingInterceptor = "com.squareup.okhttp3:logging-interceptor:$loggingInterceptorVersion"
    val roomRuntime = "androidx.room:room-runtime:$roomVersion"
    val roomCompiler = "androidx.room:room-compiler:$roomVersion"
    val roomRxJava = "androidx.room:room-rxjava2:$roomVersion"
    val lifecycleExtensions = "androidx.lifecycle:lifecycle-extensions:$lifecycleVersion"
    val lifecycleCompiler = "androidx.lifecycle:lifecycle-compiler:$lifecycleVersion"
    val lifecycleReactive = "androidx.lifecycle:lifecycle-reactivestreams:$lifecycleVersion"
    val lifecycleLiveData = "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycleVersion"
    val gson = "com.google.code.gson:gson:$gsonVersion"
    val glide = "com.github.bumptech.glide:glide:$glideVersion"
    val hilt = "com.google.dagger:hilt-android:${Version.hilt}"
    val hiltCompiler = "com.google.dagger:hilt-compiler:${Version.hilt}"

    // Http inspector
    val chucker = "com.github.chuckerteam.chucker:library:$chuckerVersion"

    // Displays network traffic in chrome browser
    val stetho = "com.facebook.stetho:stetho:$stethoVersion"
    val stethoOkHttp = "com.facebook.stetho:stetho-okhttp3:$stethoVersion"

    // Memory leak detection library
    val leakCanary = "com.squareup.leakcanary:leakcanary-android:$leakCanaryVersion"
    val detekt = "io.gitlab.arturbosch.detekt:detekt-formatting:${Version.detekt}"
}
